-- Build 122S-55: verified Stripe purchase persistence and entitlement foundation
create table if not exists public.purchase_entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  stripe_session_id text not null unique,
  stripe_event_id text not null unique,
  stripe_payment_intent_id text,
  price_id text not null,
  payment_status text not null check (payment_status = 'paid'),
  entitlement text not null default 'FOUNDING_CLIENT',
  granted_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists purchase_entitlements_user_id_idx on public.purchase_entitlements(user_id);
alter table public.purchase_entitlements enable row level security;
drop policy if exists "Users can view own purchase entitlements" on public.purchase_entitlements;
create policy "Users can view own purchase entitlements"
on public.purchase_entitlements for select
to authenticated
using (auth.uid() = user_id);
-- Writes are intentionally reserved for the server service role used by the verified Stripe webhook.
