import Link from "next/link";import {Chrome} from "./components/SiteChrome";
const worlds=[["CAREER","What else could I do?"],["BUSINESS","What could I build?"],["WHAT YOU KNOW","Could what I know become something valuable?"],["EXPERIENCES & PURSUITS","What else would I like to learn, create or experience?"],["SURPRISE ME","Show me something I wouldn’t have thought to search for."]];
export default function Page(){return <Chrome><main>
<section className="hero"><div className="hero-copy"><p className="eyebrow">CAREER · BUSINESS · REINVENTION · NEW POSSIBILITIES</p><h1>You don’t have to know<br/><em>what you’re looking for.</em></h1><h2>That’s where Discovered by Design begins.</h2><p><strong>Seeking a new career? Thinking about starting a business? Burned out or underchallenged by what’s out there?</strong></p><p>Have talents, knowledge or experience you’re not fully using? An idea, ambition or vision you never pursued? Or are you simply wondering what else might be possible?</p><p>We help you uncover new careers, business ideas, ways to use what you know, new challenges—and possibilities you may never have considered.</p><p>You may have spent years building experience, skills and interests without asking what else they could become. Or the opportunity may have nothing to do with what you’ve done before. <strong>We explore both.</strong></p><div className="hero-actions"><Link className="button gold" href="/start">Start discovering →</Link><Link className="text-link" href="/how-it-works">See how it works →</Link></div></div><div className="hero-art"><span>DISCOVER</span><span>GET INSPIRED</span><span>IMAGINE</span><span>DESIGN</span></div></section>
<div className="possibility-ribbon">CAREER <i>·</i> BUSINESS <i>·</i> WHAT YOU KNOW <i>·</i> EXPERIENCES <i>·</i> THE UNEXPECTED</div>
<section className="section read-mind"><p className="eyebrow dark">YOU DON’T NEED TO HAVE THE ANSWER</p><h2>Maybe you’re not sure what you’re looking for.</h2><div className="two-col"><div><p>Maybe you know you want a different career—but have no idea what.</p><p>Maybe you’ve always wanted a business of your own—but haven’t found the idea.</p><p>Maybe you’re successful at what you do—but you’re not sure you want to keep doing it.</p></div><div><p>Maybe you’ve accumulated years of expertise and never considered that what you know could become something valuable.</p><p>Or maybe everything is basically fine.</p><p><strong>You just have a feeling there might be something else out there for you.</strong></p></div></div><h3>That’s exactly where we begin.</h3></section>
<section className="dark-section"><p className="eyebrow">THE CENTRAL IDEA</p><h2>You can’t look for something you don’t know exists.</h2><p>That’s why we don’t begin by asking you to define the perfect career, business or future. <strong>We give you something to react to.</strong></p><div className="reaction-row"><span>NOT ME</span><span>MAYBE</span><span>CURIOUS</span><span>SHOW ME MORE</span></div><p>We learn from your reactions and introduce increasingly relevant possibilities.</p><blockquote>“I never thought of that.”</blockquote></section>
<section className="section"><p className="eyebrow dark">WHAT COULD YOU DISCOVER?</p><h2>Five worlds. No requirement to choose just one.</h2><div className="world-grid home-worlds">{worlds.map((w,i)=><article className={i===4?"world-card surprise":"world-card"} key={w[0]}><span>0{i+1}</span><h3>{w[0]}</h3><p>{w[1]}</p></article>)}</div><Link className="text-link darklink" href="/explore">Explore the possibilities →</Link></section>
<section className="life-section"><div><p className="eyebrow">A WIDER VIEW</p><h2>What’s next can be bigger than work.</h2></div><p>A business. A different career. A selective advisory role. A creative practice. Teaching. Travel. Learning. Service. A long-postponed project. Turning what you know into something valuable. Or a combination of several things that would never fit neatly inside a conventional job title.</p><h3>What’s next isn’t a single answer. It’s a field worth exploring.</h3></section>
<section className="section knowledge"><p className="eyebrow dark">WHAT YOU KNOW</p><h2>What do you know that could become something?</h2><p>You may have spent decades accumulating something you’ve never thought of as an asset: expertise, a method, a process, specialized knowledge, a training approach, research, a product idea—or simply something people constantly ask you for help with.</p><h3>What if part of what’s next is already hiding inside what you know?</h3><div className="flow">EXPERIENCE <i>→</i> EXPERTISE <i>→</i> IDEAS <i>→</i> OPPORTUNITY</div></section>
<section className="section"><p className="eyebrow dark">HOW DISCOVERY WORKS</p><div className="steps compact"><article><b>01</b><h3>Discover</h3><p>Understand where you’ve been, what energizes you and what you’d rather leave behind.</p></article><article><b>02</b><h3>Get Inspired</h3><p>Encounter careers, businesses, ideas, experiences and possibilities you may never have considered.</p></article><article><b>03</b><h3>Imagine</h3><p>See how an interesting possibility could work differently in your life.</p></article><article><b>04</b><h3>Design</h3><p>Investigate what deserves attention and create a practical way forward.</p></article></div><h3 className="method-line">Possibility before prescription. <span>Expand the field before narrowing it.</span></h3></section>
<section className="curiosity"><h2>You don’t have to find your passion.</h2><p>Start by finding what makes you curious.</p><strong>Curiosity is enough to begin.</strong></section>
<section className="section experience"><p className="eyebrow dark">YOU’RE NOT STARTING OVER</p><h2>You’re starting with experience.</h2><p>Everything you’ve learned matters. What you’ve enjoyed matters. What you’ve disliked matters. Your successes matter. Your mistakes matter. And what you’ve always wondered about matters.</p><h3>The question isn’t simply, “What have I done?”<br/><em>It’s “What could I do with everything I know now?”</em></h3></section>
<section className="blueprint-preview"><div><p className="eyebrow">YOUR PERSONALIZED BLUEPRINT</p><h2>Not one answer. A better field of view.</h2><p>Your Blueprint brings together what we discovered, the patterns we noticed, possibilities worth exploring, why they surfaced, practical realities and ways to begin.</p><p><strong>It doesn’t decide what’s next for you. It helps you see what deserves a closer look.</strong></p><Link className="button gold" href="/blueprint">Explore your Blueprint →</Link></div><div className="mini-sheet"><span>WHAT WE DISCOVERED</span><span>POSSIBILITIES WORTH EXPLORING</span><span>THE UNEXPECTED</span><span>DEEP DIVES</span><span>YOUR NEXT 90 DAYS</span></div></section>
<section className="final-cta"><p className="eyebrow dark">STILL NOT SURE WHAT YOU’RE LOOKING FOR?</p><h2>Good. You don’t need to be.</h2><p>You don’t need the idea. You don’t need the plan. You don’t need the answer.</p><h3>You just need enough curiosity to begin.</h3><Link className="button dark-button" href="/start">Help me find what’s next →</Link></section>
</main></Chrome>}
