const $=s=>document.querySelector(s);
const sections=[
{id:"chapter",name:"Where You Are Now",questions:[["scale","I feel clear about what I want the next three to five years to contain."],["scale","My current weekly life reflects what matters most to me."],["choice","Which statement feels closest to your current situation?",["Planning ahead for a transition","Actively moving through a transition","Transitioned but still finding my rhythm","Life is stable, but I want it to become more intentional"]],["text","What feels most unfinished, uncertain or interesting about your next chapter?"]]},
{id:"energy",name:"Energy & Engagement",questions:[["scale","I regularly do things that leave me feeling energized rather than merely occupied."],["scale","There is something meaningful on my calendar that I genuinely look forward to."],["multi","Which activities tend to give you energy?",["Solving problems","Creating or making","Teaching or mentoring","Learning","Travel and exploration","Family time","Community or service","Physical activity / outdoors","Quiet reflection","Building something new"]],["text","Think of a recent day that felt especially worthwhile. What were you doing?"]]},
{id:"expertise",name:"Experience & Expertise",questions:[["scale","I still want to use some of my professional knowledge or accumulated experience."],["scale","People seek my judgment, perspective or practical knowledge."],["multi","Which forms of contribution interest you?",["Consulting or advisory work","Starting a business","Teaching","Mentoring","Writing or speaking","Board or nonprofit work","Creative work","I would rather leave professional work behind"]],["text","What do you know now that took years to learn?"]]},
{id:"possibility",name:"Possibility & Reinvention",questions:[["scale","There is something I have postponed that I would regret never exploring."],["scale","I am comfortable testing a new direction without knowing whether it will become permanent."],["multi","What possibilities attract you right now?",["Start something","Earn selectively","Teach / mentor","Create","Travel / explore","Learn","Give back","Spend more time with family","Preserve my story","Simplify"]],["text","If success were not required, what would you be curious enough to try?"]]},
{id:"freedom",name:"Freedom & Constraints",questions:[["scale","I have meaningful control over how I use my time."],["scale","My obligations leave room for experimentation and change."],["multi","What currently limits your freedom most?",["Work responsibilities","Family / caregiving","Property / home responsibilities","Financial uncertainty","Health or energy","Geography","Too many commitments","Other people's expectations","I do not feel significantly constrained"]],["text","What would you remove, reduce, delegate or simplify if you gave yourself permission?"]]},
{id:"relationships",name:"People & Place",questions:[["scale","I am intentional about spending time with the people who matter most."],["scale","Where I live supports the life I want now."],["multi","Which areas deserve more attention?",["Spouse / partner","Children","Grandchildren","Friends","New social connections","Community","Where I live","Travel with people I care about","Time alone / independence"]],["text","What relationship, tradition or shared experience would you most like to strengthen?"]]},
{id:"continuity",name:"Organization & Continuity",questions:[["scale","A trusted person could locate the information needed to manage important household affairs if I were unavailable."],["scale","My important documents, contacts and household information are reasonably organized and current."],["multi","Which areas could be easier to navigate?",["Important contacts","Financial account inventory","Insurance information","Property information","Estate documents","Digital information","Recurring household responsibilities","Personal wishes / instructions","Everything is reasonably organized"]],["text","What important household knowledge currently exists mostly in your head?"]]},
{id:"legacy",name:"Legacy & What Matters",questions:[["scale","I have thought about what I want people I love to remember about me."],["scale","I am actively preserving stories, lessons, photographs, traditions or family history."],["multi","What would you most like to carry forward?",["Family stories","Values and lessons","Traditions","Photographs and history","Messages to people I love","Philanthropic impact","Knowledge / expertise","Creative work","Family continuity"]],["text","What is one story, lesson or belief you would not want to disappear with you?"]]}];
const labels=["Not at all","A little","Somewhat","Mostly","Very much"];let state={section:0,q:0,answers:{},started:false,completed:false,version:"sla_proto_v1.0"};
try{let x=JSON.parse(localStorage.getItem("next25SLA"));if(x&&x.version===state.version)state=x}catch(e){}
const key=()=>sections[state.section].id+"_"+state.q,total=()=>sections.reduce((n,s)=>n+s.questions.length,0),pct=()=>Math.round(Object.keys(state.answers).length/total()*100);
function save(){localStorage.setItem("next25SLA",JSON.stringify(state));$("#saveText").textContent="Saved just now";setTimeout(()=>$("#saveText").textContent="Saved in this browser",900)}
function done(i){return sections[i].questions.every((q,n)=>state.answers[sections[i].id+"_"+n]!==undefined)}
function nav(){ $("#sectionNav").innerHTML=sections.map((s,i)=>`<button data-i="${i}" class="${i===state.section&&state.started?"active":""}"><b>${String(i+1).padStart(2,"0")}</b><span>${s.name}</span>${done(i)?"<i>✓</i>":""}</button>`).join("");document.querySelectorAll("#sectionNav button").forEach(b=>b.onclick=()=>{if(state.started){state.section=+b.dataset.i;state.q=0;render()}})}
function progress(){ $("#assessmentBar").style.width=pct()+"%";nav()}
$("#beginAssessment").onclick=()=>{state.started=true;save();render()};if(state.started&&!state.completed){$("#resumeAssessment").hidden=false;$("#resumeAssessment").onclick=render}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(){ $("#assessmentIntro").hidden=true;$("#assessmentComplete").hidden=true;$("#assessmentQuestion").hidden=false;let s=sections[state.section],q=s.questions[state.q],v=state.answers[key()],input="";
if(q[0]==="scale")input=`<div class="answer-scale">${labels.map((x,i)=>`<button data-v="${i}" class="${v===i?"selected":""}"><b>${i}</b><span>${x}</span></button>`).join("")}</div>`;
if(q[0]==="choice")input=`<div class="answer-choices">${q[2].map(x=>`<button data-v="${esc(x)}" class="${v===x?"selected":""}">${x}</button>`).join("")}</div>`;
if(q[0]==="multi"){let a=Array.isArray(v)?v:[];input=`<p class="helper">Select any that apply.</p><div class="answer-multi">${q[2].map(x=>`<button data-v="${esc(x)}" class="${a.includes(x)?"selected":""}">${x}</button>`).join("")}</div>`}
if(q[0]==="text")input=`<textarea id="textAnswer" rows="7" maxlength="1200" placeholder="Write as much or as little as feels useful...">${esc(v||"")}</textarea>`;
$("#assessmentQuestion").innerHTML=`<div class="question-meta"><span>SECTION ${state.section+1} OF 8</span><span>${s.name}</span><span>${pct()}% complete</span></div><p class="question-number">QUESTION ${state.q+1} OF ${s.questions.length}</p><h2>${q[1]}</h2>${input}<div class="assessment-actions"><button class="text-btn" id="back">← Back</button><button class="button" id="next">${state.section===7&&state.q===3?"Complete Assessment":"Continue →"}</button></div>`;
document.querySelectorAll(".answer-scale button,.answer-choices button").forEach(b=>b.onclick=()=>{state.answers[key()]=q[0]==="scale"?+b.dataset.v:b.dataset.v;save();render()});
document.querySelectorAll(".answer-multi button").forEach(b=>b.onclick=()=>{let a=Array.isArray(state.answers[key()])?[...state.answers[key()]]:[],x=b.dataset.v;state.answers[key()]=a.includes(x)?a.filter(y=>y!==x):[...a,x];save();render()});
$("#back").onclick=back;$("#next").onclick=next;progress()}
function capture(){let t=$("#textAnswer");if(t){let v=t.value.trim();if(v)state.answers[key()]=v;else delete state.answers[key()];save()}}
function next(){capture();if(state.answers[key()]===undefined){alert("Please answer this question before continuing.");return}if(state.section===7&&state.q===3){state.completed=true;save();complete();return}if(state.q<3)state.q++;else{state.section++;state.q=0}save();render()}
function back(){capture();if(state.section===0&&state.q===0){state.started=false;save();location.reload();return}if(state.q)state.q--;else{state.section--;state.q=3}save();render()}
function complete(){$("#assessmentIntro").hidden=true;$("#assessmentQuestion").hidden=true;$("#assessmentComplete").hidden=false;$("#assessmentBar").style.width="100%";$("#assessmentComplete").innerHTML=`<p class="eyebrow">ASSESSMENT COMPLETE</p><h1>You have created the raw material for your NEXT25 Blueprint™.</h1><p class="lead">This prototype organizes your responses so a future Blueprint engine can identify themes, opportunities and experiments worth considering.</p><div class="completion-stats"><span><b>32</b>questions completed</span><span><b>8</b>life areas explored</span><span><b>100%</b>complete</span></div><div class="blueprint-next"><p class="kicker">PLANNED BLUEPRINT PIPELINE</p><h3>Your answers → structured interpretation → personalized possibilities → 25 for 25™ → 90-Day Experiments™</h3><p>For now, your answers remain only on this device.</p></div><div class="assessment-actions"><button class="text-btn" id="review">Review answers</button><a class="button" href="index.html#sample-blueprint">View Sample Blueprint™ →</a></div><button class="danger-link" id="clear">Clear prototype assessment from this browser</button>`;$("#review").onclick=()=>{state.completed=false;state.section=0;state.q=0;save();render()};$("#clear").onclick=()=>{if(confirm("Clear all saved prototype answers?")){localStorage.removeItem("next25SLA");location.reload()}};progress()}
nav();if(state.completed)complete();