const $=s=>document.querySelector(s);
$("#year").textContent=new Date().getFullYear();
const menu=$(".menu"); if(menu) menu.addEventListener("click",()=>$(".site-header nav").classList.toggle("open"));
const form=$("#foundingForm"), steps=[...document.querySelectorAll(".form-step")];
let current=0;
function showStep(n){steps.forEach((s,i)=>{s.hidden=i!==n;s.classList.toggle("active",i===n)});current=n;if(n===2)renderReview();form.scrollIntoView({behavior:"smooth",block:"center"})}
function validateStep(n){const fields=[...steps[n].querySelectorAll("[required]")];for(const f of fields){if(!f.checkValidity()){f.reportValidity();return false}}return true}
document.querySelectorAll(".form-next").forEach(b=>b.addEventListener("click",()=>{if(validateStep(current))showStep(Math.min(current+1,2))}));
document.querySelectorAll(".form-back").forEach(b=>b.addEventListener("click",()=>showStep(Math.max(current-1,0))));
function renderReview(){const d=new FormData(form);$("#enrollReview").innerHTML=`<div><small>NAME</small><strong>${esc(d.get("firstName"))} ${esc(d.get("lastName"))}</strong></div><div><small>EMAIL</small><strong>${esc(d.get("email"))}</strong></div><div><small>STAGE</small><strong>${esc(d.get("stage"))}</strong></div><div><small>PRIMARY INTEREST</small><strong>${esc(d.get("interest"))}</strong></div>`}
function esc(v){return String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
form.addEventListener("submit",e=>{e.preventDefault();if(!validateStep(2))return;steps[2].hidden=true;const d=new FormData(form), first=esc(d.get("firstName"));$("#enrollSuccess").hidden=false;$("#enrollSuccess").innerHTML=`<p class="eyebrow">PREVIEW ENROLLMENT COMPLETE</p><h3>Thank you, ${first}.</h3><p>In the live version, the next button will open a secure hosted checkout. After successful payment, you will be directed to the Second Life Architect™ assessment and welcome experience.</p><div class="checkout-preview"><span>FOUNDING CLIENT</span><strong>$595</strong><small>Secure hosted payment processor to be connected</small></div><button type="button" id="paymentPreview" class="button">Preview Checkout Step</button><p><a class="text-link" href="assessment.html">Preview the Second Life Architect™ assessment →</a></p>`;$("#paymentPreview").addEventListener("click",()=>openModal(`<div class="checkout-box"><p class="eyebrow">SECURE CHECKOUT PLACEHOLDER</p><h2>Second Life Architect™</h2><div class="price">$595</div><p>This is where NEXT25 will redirect the customer to a secure hosted payment page such as Stripe Checkout, PayPal or another selected provider.</p><p><strong>No raw credit-card information will be collected by this GitHub Pages site.</strong></p><hr><h3>After payment</h3><p>Successful payment → Welcome → Second Life Architect™ assessment → Blueprint production → Delivery.</p></div>`))});
function openModal(html){$("#modalContent").innerHTML=html;$("#modal").hidden=false}
$("#closeModal").addEventListener("click",()=>$("#modal").hidden=true);
$("#modal").addEventListener("click",e=>{if(e.target.id==="modal")$("#modal").hidden=true});
