const S={energy:[],want:[],expertise:[]};
document.querySelectorAll(".chips").forEach(g=>g.querySelectorAll("button").forEach(b=>b.onclick=()=>{let k=g.dataset.g,m=+g.dataset.max,v=b.dataset.v;if(S[k].includes(v)){S[k]=S[k].filter(x=>x!=v);b.classList.remove("selected");return}if(m==1){g.querySelectorAll("button").forEach(x=>x.classList.remove("selected"));S[k]=[v]}else{if(S[k].length>=m)return;S[k].push(v)}b.classList.add("selected")}));
const P=[
["Specialized Advisory Studio","EXPERTISE → INDEPENDENCE",["solve","research","autonomy","income","flexibility","reuse","reshape"],"Turn hard-earned judgment into selective project-based advisory work.","Write a one-page offer around one expensive problem you solve well and show it to three people."],
["Fractional Expert Role","EXPERTISE → FLEXIBILITY",["solve","people","autonomy","income","flexibility","reuse","reshape"],"Provide senior-level judgment without recreating a full-time job.","Identify three organizations that could use your expertise a few days each month."],
["Private Workshop Practice","TEACHING → EXPERTISE",["teach","people","meaning","income","impact","reuse","reshape","create"],"Package one area of expertise into intimate workshops or executive education.","Teach one 60-minute pilot to 6–10 people and measure demand and your energy."],
["Mentor-in-Residence","MENTORING → CONTRIBUTION",["teach","people","meaning","impact","flexibility","reuse","reshape"],"Offer structured mentoring inside a company, association or community.","Mentor three people around the same recurring problem and note what they consistently need."],
["Niche Research Briefing","CURIOSITY → INTELLECTUAL PROPERTY",["research","solve","autonomy","income","creative","reuse","reshape"],"Turn deep research into paid intelligence, briefings or decision support.","Create one unusually useful five-page briefing for a narrowly defined audience."],
["Micro-Consultancy","INDEPENDENCE → SMALL BUSINESS",["solve","build","autonomy","income","flexibility","reshape"],"Build a deliberately small specialist firm around one valuable problem.","Define one customer, one problem and one fixed-scope service; seek one paid pilot."],
["Knowledge Product Studio","EXPERTISE → CREATION",["teach","create","research","autonomy","creative","income","reuse","reshape"],"Turn expertise into guides, courses, tools, templates or publications.","Create the smallest useful paid artifact you can finish in two weeks."],
["Portfolio Career","VARIETY → FREEDOM",["explore","people","solve","flexibility","novelty","income","reshape","unsure"],"Combine several smaller roles instead of choosing one identity.","Sketch three different weekly portfolios and test one element from each."],
["Acquisition Entrepreneur","OWNERSHIP → EXISTING BUSINESS",["build","solve","autonomy","income","reuse","reshape"],"Explore buying an established small business rather than starting at zero.","Study ten businesses for sale in one sector only to learn what attracts or repels you."],
["Curated Experience Business","EXPLORATION → ENTREPRENEURSHIP",["explore","people","create","autonomy","creative","novelty","leave","reshape"],"Design specialized trips, learning experiences or gatherings around an interest.","Design one one-day experience for six people and test whether you enjoy curation and hosting."],
["Independent Creative Practice","CREATION → NEW IDENTITY",["create","research","creative","meaning","autonomy","novelty","leave"],"Give a serious creative interest enough structure to become a meaningful practice.","Finish and share one piece each week for six weeks; track energy and outside pull."],
["Community Problem Lab","SERVICE → PROJECT",["solve","people","build","impact","meaning","leave"],"Organize a time-bounded project around solving one concrete community problem.","Interview five people closest to the problem before proposing a solution."],
["Learning Sabbatical","CURIOSITY → REINVENTION",["research","explore","novelty","meaning","flexibility","leave","unsure"],"Use a defined period of learning and field exposure to discover a new direction.","Build a six-week personal curriculum with two real-world conversations each week."]
];
const N={solve:"problem solving",teach:"teaching",create:"creation",people:"helping people",research:"curiosity",build:"building",explore:"exploration",autonomy:"independence",meaning:"meaning",income:"selective income",flexibility:"flexibility",creative:"creative expression",impact:"contribution",novelty:"novelty",reuse:"existing expertise",reshape:"reshaped expertise",leave:"new identity",unsure:"open exploration"};
document.querySelector("#generate").onclick=()=>{if(!S.energy.length||!S.want.length||!S.expertise.length){help.textContent="Please choose at least one answer in each group.";return}let A=[...S.energy,...S.want,...S.expertise],R=P.map(p=>[...p,A.filter(x=>p[2].includes(x)).length]).sort((a,b)=>b[5]-a[5]).slice(0,5);results.innerHTML=`<div class="pattern"><p class="eyebrow">YOUR POSSIBILITY PATTERN</p><h3>${A.map(x=>N[x]).slice(0,6).join(" + ")}</h3><p>These signals do not determine an answer. They change which possibilities deserve investigation.</p></div>${R.map((p,i)=>`<article class="match"><div><small>0${i+1} • ${p[1]}</small><h3>${p[0]}</h3><p>${p[3]}</p></div><aside><b>WHY IT SURFACED</b><p>${A.filter(x=>p[2].includes(x)).map(x=>N[x]).join(" • ")}</p><b>SMALL TEST</b><p>${p[4]}</p></aside></article>`).join("")}<div class="boundary"><b>What this does not mean</b><p>These are possibilities to investigate, not recommendations or predictions. A strong match on paper can still be wrong in real life. The next step is evidence.</p></div>`;results.scrollIntoView({behavior:"smooth"})};