import Link from "next/link";import {Chrome} from "../components/SiteChrome";
import {assembleBlueprint} from "../../lib/discovery/blueprintAssembly";
const chapters=[
 ["01","WHAT WE DISCOVERED","The signals, reactions and recurring themes that began to matter."],
 ["02","YOUR EMERGING PROFILE","A working picture of how you may want to work, create, contribute and live—not a personality label."],
 ["03","MORE OF · LESS OF","The conditions that appear to create energy, and the conditions you would prefer to discard."],
 ["04","YOUR DISCOVERY FIELD","A curated field of possibilities—not a ranked winner."],
 ["05","POSSIBILITIES WORTH EXPLORING","Directions with enough evidence to deserve deeper investigation."],
 ["06","THE UNEXPECTED","Ideas kept deliberately outside the obvious path to prevent discovery from becoming résumé matching."],
 ["07","WHAT YOU KNOW","Experience, expertise, ideas, methods and know-how that may have applications you have not considered."],
 ["08","OPPORTUNITY DEEP DIVES","What the work involves, entry routes, economics, requirements, risks, poor-fit signals and unanswered questions."],
 ["09","EXPERIMENTS","Small ways to gather evidence before making a large career, business or lifestyle commitment."],
 ["10","QUESTIONS STILL WORTH ANSWERING","The uncertainties that matter enough to research rather than guess about."],
 ["11","YOUR NEXT 90 DAYS","A practical sequence for learning, testing and narrowing without forcing a premature decision."]
];
const sample=[["STRONG CURIOSITY","Independent, intellectually challenging work"],["PATTERN","Expertise + explanation + autonomy"],["CONDITIONS TO DISCARD","Heavy management · fixed structure · unnecessary administration"],["DISCOVERY PRINCIPLE","Possibility before prescription"]];
export default function Page(){
 const assembled=assembleBlueprint({signals:["Independence","Intellectual challenge","Teaching"],discard:["Employee management","Fixed schedules","Heavy administration"],field:["Specialty Research & Insight Practice","Fractional Strategic Adviser","Expert-Led Learning Studio","Methodology Productization"],unexpected:["Independent Project Producer","Apprentice-to-Expert Reset"],briefs:["Specialty Research & Insight Practice","Fractional Strategic Adviser"],experiments:["Teach one workshop · 14-day test"],knowledge:["Explain complex ideas","Improve repeatable processes"],openQuestions:["How much selling feels acceptable?","Which direction creates energy in real practice?"]});return <Chrome><div className="assembly-preview"><div><p className="eyebrow">BLUEPRINT ASSEMBLY ENGINE · BUILD 21</p><h2>Your discovery is becoming a document.</h2><p>The Blueprint is assembled from evidence gathered across discovery—not from a single test or generic template.</p></div><div className="assembly-flow">{assembled.map(s=><span key={s.number}><b>{s.number}</b>{s.title}<small>{s.items.length} evidence item{s.items.length===1?"":"s"}</small></span>)}</div><p className="assembly-boundary">Illustrative assembly preview. Production output will use the authenticated customer’s persisted Discovery Record, research and experiments after the secure data connection is completed.</p></div><main>
<section className="page-hero blueprint-hero"><p className="eyebrow">YOUR PERSONALIZED DISCOVERY BLUEPRINT</p><h1>From “What if?” to “What would this actually take?”</h1><p className="lead">Not one answer. A better field of view—and a practical way to investigate what deserves a closer look.</p><div className="blueprint-hero-actions"><Link className="button gold" href="/start">Begin my discovery →</Link><a className="button ghost-button" href="#preview">See inside the Blueprint ↓</a></div></section>
<section className="section blueprint-intro"><div><p className="eyebrow dark">THE PRODUCT</p><h2>This is where discovery becomes something you can use.</h2><p>Your Blueprint brings together what caught your attention, what you rejected, the patterns beginning to emerge, possibilities worth exploring, unexpected directions, what may be hiding inside what you already know, and the practical questions that should be answered before commitment.</p><blockquote>It doesn’t decide what’s next for you. It helps you see what deserves a closer look—and how to investigate it.</blockquote></div><div className="blueprint-cover"><span>DISCOVERED BY DESIGN™</span><small>PERSONALIZED DISCOVERY BLUEPRINT</small><h3>WHAT COULD COME NEXT?</h3><i>Discovery · Possibility · Research · Design</i></div></section>
<section id="preview" className="blueprint-preview"><div className="preview-title"><p className="eyebrow">INSIDE YOUR BLUEPRINT</p><h2>A record of what we discovered—and a map for what to investigate next.</h2></div><div className="blueprint-chapters">{chapters.map(x=><article key={x[0]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section>
<section className="section sample-spread"><div><p className="eyebrow dark">A SAMPLE DISCOVERY SPREAD</p><h2>We show the evidence before the conclusion.</h2><p>A useful Blueprint should let you see why a direction surfaced. It should also preserve uncertainty where the evidence is incomplete.</p><div className="sample-signals">{sample.map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div></div><div className="sample-page"><span>07 · POSSIBILITY DEEP DIVE</span><h3>Specialty Research & Insight Practice</h3><p className="sample-lead">A possible expression of deep expertise, independent work and explaining difficult subjects—without assuming you want to recreate a conventional firm.</p><hr/><b>WHY IT SURFACED</b><p>Your reactions suggest interest in intellectual challenge, autonomy and specialized knowledge. The question is whether the actual research, client development and delivery model would energize you.</p><b>WHAT TO INVESTIGATE</b><p>Who buys specialized insight? What problem is valuable enough to pay for? What does a realistic week look like? How concentrated is demand? What would a credible first offer require?</p><b>SMALL EXPERIMENT</b><p>Choose one narrowly defined issue, interview five potential users of the insight, and create one sample briefing before building a business around it.</p></div></section>
<section className="blueprint-90"><div><p className="eyebrow">YOUR NEXT 90 DAYS</p><h2>Evidence before commitment.</h2><p>The Blueprint should end with movement, not another abstract report.</p></div><div className="days"><article><b>01–30</b><h3>Investigate</h3><p>Validate the people, work, economics, requirements and assumptions behind the most interesting possibilities.</p></article><article><b>31–60</b><h3>Experiment</h3><p>Run small tests: conversations, workshops, sample work, shadowing, prototypes or bounded projects.</p></article><article><b>61–90</b><h3>Refine</h3><p>Keep, reshape or reject directions based on evidence—and decide what deserves another round.</p></article></div></section>
<section className="section blueprint-close"><p className="eyebrow dark">DISCOVER · INVESTIGATE · DESIGN</p><h2>You don’t need one perfect answer.</h2><p>You need better possibilities, better evidence and a practical way to decide what deserves more of your attention.</p><Link className="button dark-button" href="/start">Help me find what’s next →</Link><small>Blueprint content shown here is illustrative. A personalized Blueprint is built from the customer’s own discovery signals and requires deeper research before specific factual, economic, licensing or regulatory conclusions are presented.</small></section>
</main></Chrome>}