"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Chrome} from "../components/SiteChrome";
import {assembleBlueprint} from "../../lib/discovery/blueprintAssembly";
import {possibilityUniverse} from "../../lib/discovery/possibilities";
import type {DiscoveryRecord} from "../../lib/discovery/record";

const chapters=[
["01","WHAT WE DISCOVERED","The signals, reactions and recurring themes that began to matter."],
["02","YOUR EMERGING PROFILE","A working picture of how you may want to work, create, contribute and live—not a personality label."],
["03","MORE OF · LESS OF","The conditions that appear to create energy, and the conditions you would prefer to discard."],
["04","YOUR DISCOVERY FIELD","A curated field of possibilities—not a ranked winner."],
["05","POSSIBILITIES WORTH EXPLORING","Directions with enough evidence to deserve deeper investigation."],
["06","THE UNEXPECTED","Ideas kept deliberately outside the obvious path to prevent discovery from becoming résumé matching."],
["07","WHAT YOU KNOW","Experience, expertise, ideas, methods and know-how that may have applications you have not considered."],
["08","OPPORTUNITY DEEP DIVES","What the work involves, entry routes, economics, requirements, risks, poor-fit signals and unanswered questions."],
["09","EXPERIMENTS","Small ways to gather evidence before making a large career, business or lifestyle commitment."],
["10","QUESTIONS STILL WORTH ANSWERING","The uncertainties that matter enough to research rather than guess about."],
["11","YOUR NEXT 90 DAYS","A practical sequence for learning, testing and narrowing without forcing a premature decision."]
];
const fallback={signals:["Complete more discovery to reveal your strongest signals."],discard:["Add Conditions to Discard during discovery."],field:["Keep possibilities in your Discovery Field to see them here."],unexpected:["Surprise Me directions will appear as your field develops."],knowledge:["Complete What You Know reflections to surface reusable experience."],briefs:["Open Opportunity Briefs to add research directions."],experiments:["Plan a small experiment to add real-world evidence."],openQuestions:["What deserves a closer look next?"]};
export default function Page(){
 const [record,setRecord]=useState<DiscoveryRecord|null>(null),[state,setState]=useState<"loading"|"ready"|"signed-out"|"error">("loading");
 useEffect(()=>{fetch("/api/discovery").then(async r=>{if(r.status===401){setState("signed-out");return}if(!r.ok)throw new Error();const j=await r.json();setRecord(j?.record?.record||null);setState("ready")}).catch(()=>setState("error"))},[]);
 const input=useMemo(()=>{if(!record)return fallback;
  const field=Object.entries(record.fieldActions||{}).filter(([,v])=>v!=="DISCARD").map(([k])=>k);
  const unexpected=field.filter(t=>possibilityUniverse.find(p=>p.title===t)?.lane==="SURPRISE ME");
  const knowledge=Object.values(record.knowledge||{}).map(x=>x.trim()).filter(Boolean).slice(0,6);
  const experiments=(record.experiments||[]).map(x=>`${x.possibility} · ${x.time} · ${x.status}`);
  const openQuestions=[...new Set(Object.values(record.rejectionReasons||{}).flat().map(x=>`What would make “${x}” acceptable—or confirm it should remain discarded?`))].slice(0,4);
  return {signals:record.wantMore.length?record.wantMore:fallback.signals,discard:record.wantLess.length?record.wantLess:fallback.discard,field:field.length?field:fallback.field,unexpected:unexpected.length?unexpected:fallback.unexpected,knowledge:knowledge.length?knowledge:fallback.knowledge,briefs:record.briefsOpened.length?record.briefsOpened:fallback.briefs,experiments:experiments.length?experiments:fallback.experiments,openQuestions:openQuestions.length?openQuestions:fallback.openQuestions};
 },[record]);
 const assembled=useMemo(()=>assembleBlueprint(input),[input]);
 const live=Boolean(record);
 return <Chrome><div className="assembly-preview"><div><p className="eyebrow">YOUR BLUEPRINT · LIVE ASSEMBLY</p><h2>{live?"Your discovery is becoming your document.":"Your Blueprint grows as your discovery grows."}</h2><p>{state==="loading"?"Loading your Discovery Record…":state==="signed-out"?"Sign in to assemble a saved personalized Blueprint.":"The Blueprint assembles evidence from your discovery, field decisions, research and experiments—not from a single test."}</p></div><div className="assembly-flow">{assembled.map(s=><span key={s.number}><b>{s.number}</b>{s.title}<small>{s.items.length} evidence item{s.items.length===1?"":"s"}</small></span>)}</div><p className="assembly-boundary">{live?"PERSONALIZED · Built from your current authenticated Discovery Record. Research items remain questions until independently verified.":"PREVIEW · Begin discovery and save your record to replace these prompts with your own evidence."}</p></div><main>
<section className="page-hero blueprint-hero"><p className="eyebrow">YOUR PERSONALIZED DISCOVERY BLUEPRINT</p><h1>From “What if?” to “What would this actually take?”</h1><p className="lead">Not one answer. A better field of view—and a practical way to investigate what deserves a closer look.</p><div className="blueprint-hero-actions"><Link className="button gold" href="/start">{live?"Continue my discovery →":"Begin my discovery →"}</Link><a className="button ghost-button" href="#evidence">See my Blueprint evidence ↓</a></div></section>
<section id="evidence" className="section blueprint-intro"><div><p className="eyebrow dark">YOUR EVIDENCE</p><h2>{live?"This is what your discovery has produced so far.":"Your Blueprint begins with evidence, not a verdict."}</h2><p>It brings together what caught your attention, what you want to discard, possibilities you preserved, unexpected directions, knowledge you may be able to reuse, research activity and experiments.</p><blockquote>It doesn’t decide what’s next for you. It helps you see what deserves a closer look—and how to investigate it.</blockquote></div><div className="blueprint-cover"><span>DISCOVERED BY DESIGN™</span><small>PERSONALIZED DISCOVERY BLUEPRINT</small><h3>WHAT COULD COME NEXT?</h3><i>Discovery · Possibility · Research · Design</i></div></section>
<section className="blueprint-preview"><div className="preview-title"><p className="eyebrow">CURRENT BLUEPRINT ASSEMBLY</p><h2>A living record of what you discovered—and what deserves investigation next.</h2></div><div className="blueprint-chapters">{assembled.map(s=><article key={s.number}><b>{s.number}</b><div><h3>{s.title}</h3><p>{s.purpose}</p><small>{s.status}</small>{s.items.map(x=><p key={x}>→ {x}</p>)}</div></article>)}</div></section>
<section className="section sample-spread"><div><p className="eyebrow dark">THE FULL BLUEPRINT</p><h2>Evidence first. Conclusions later.</h2><p>The finished Blueprint preserves uncertainty where evidence is incomplete and distinguishes your reactions from facts that still require research.</p><div className="sample-signals"><div><span>STRONG SIGNALS</span><strong>{input.signals.slice(0,3).join(" · ")}</strong></div><div><span>CONDITIONS TO DISCARD</span><strong>{input.discard.slice(0,3).join(" · ")}</strong></div><div><span>FIELD</span><strong>{input.field.slice(0,3).join(" · ")}</strong></div><div><span>EXPERIMENTS</span><strong>{input.experiments.slice(0,2).join(" · ")}</strong></div></div></div><div className="sample-page"><span>YOUR DISCOVERY FIELD</span><h3>{input.field[0]}</h3><p className="sample-lead">This direction remains visible because of choices made in your Discovery Field. It is not a recommendation or prediction.</p><hr/><b>WHAT TO INVESTIGATE</b><p>{input.openQuestions[0]}</p><b>WHAT YOU KNOW</b><p>{input.knowledge[0]}</p><b>SMALL EXPERIMENT</b><p>{input.experiments[0]}</p></div></section>
<section className="blueprint-90"><div><p className="eyebrow">YOUR NEXT 90 DAYS</p><h2>Evidence before commitment.</h2><p>The Blueprint should end with movement, not another abstract report.</p></div><div className="days"><article><b>01–30</b><h3>Investigate</h3><p>Validate the people, work, economics, requirements and assumptions behind the most interesting possibilities.</p></article><article><b>31–60</b><h3>Experiment</h3><p>Run small tests: conversations, workshops, sample work, shadowing, prototypes or bounded projects.</p></article><article><b>61–90</b><h3>Refine</h3><p>Keep, reshape or reject directions based on evidence—and decide what deserves another round.</p></article></div></section>
<section className="section blueprint-close"><p className="eyebrow dark">DISCOVER · INVESTIGATE · DESIGN</p><h2>You don’t need one perfect answer.</h2><p>You need better possibilities, better evidence and a practical way to decide what deserves more of your attention.</p><Link className="button dark-button" href="/start">Continue building my Blueprint →</Link><small>Discovery evidence reflects the customer’s own responses. Specific factual, economic, licensing, legal, tax and regulatory conclusions require current research and, where appropriate, qualified professional review.</small></section>
</main></Chrome>
}