"use client";
import {useEffect,useRef,useState} from "react";import Link from "next/link";
type Lane="KEEP IN VIEW"|"INVESTIGATE"|"EXPERIMENT"|"DISCARD";
const seed=[
 {title:"Specialty Research & Insight Practice",world:"BUSINESS",lane:"INVESTIGATE" as Lane,note:"Deep expertise · independent work · explaining complex subjects"},
 {title:"Fractional Strategic Adviser",world:"CAREER",lane:"KEEP IN VIEW" as Lane,note:"Experience without rebuilding a full operating role"},
 {title:"Expert-Led Learning Studio",world:"BUSINESS",lane:"EXPERIMENT" as Lane,note:"Teaching · intellectual challenge · productized expertise"},
 {title:"Methodology Productization",world:"WHAT YOU KNOW",lane:"KEEP IN VIEW" as Lane,note:"Turn a repeatable method into something teachable or licensable"},
 {title:"Curated Salon or Learning Circle",world:"EXPERIENCE",lane:"DISCARD" as Lane,note:"A useful rejection still teaches the discovery system"}
];
const lanes:Lane[]=["KEEP IN VIEW","INVESTIGATE","EXPERIMENT","DISCARD"];
const copy:Record<Lane,string>={"KEEP IN VIEW":"Interesting enough to preserve without forcing a decision.","INVESTIGATE":"Worth deeper research through an Opportunity Brief or Blueprint.","EXPERIMENT":"Strong enough to test with a small real-world experiment.","DISCARD":"Out of the active field—but preserved as useful discovery evidence."};
export default function FieldPage(){const [items,setItems]=useState(seed);const [save,setSave]=useState("loading");const record=useRef<any>(null);useEffect(()=>{fetch("/api/discovery").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(j=>{record.current=j?.record?.record||null;const actions=record.current?.fieldActions||{};setItems(v=>v.map(x=>actions[x.title]?{...x,lane:actions[x.title] as Lane}:x));setSave("ready")}).catch(()=>setSave("local"))},[]);const move=(title:string,lane:Lane)=>{setItems(v=>v.map(x=>x.title===title?{...x,lane}:x));if(record.current){setSave("saving");record.current={...record.current,fieldActions:{...(record.current.fieldActions||{}),[title]:lane}};fetch("/api/discovery",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(record.current)}).then(r=>setSave(r.ok?"saved":"local")).catch(()=>setSave("local"))}};return <main className="field-workspace"><header><Link href="/dashboard">← Where You Are Now</Link><span>DISCOVERED BY DESIGN™</span><Link href="/blueprint">My Blueprint →</Link></header><section className="field-workspace-hero"><p className="eyebrow dark">MY DISCOVERY FIELD</p><h1>We expand the field.<br/>You decide what stays in it.</h1><p>Move possibilities as your thinking changes. Nothing here is a score, ranking or final recommendation.</p></section><section className="field-board">{lanes.map(lane=><div className={"field-column "+(lane==="DISCARD"?"discard-column":"")} key={lane}><div className="field-column-head"><span>{lane}</span><b>{items.filter(x=>x.lane===lane).length}</b><p>{copy[lane]}</p></div>{items.filter(x=>x.lane===lane).map(x=><article className="field-card" key={x.title}><small>{x.world}</small><h2>{x.title}</h2><p>{x.note}</p><label>MOVE TO<select value={x.lane} onChange={e=>move(x.title,e.target.value as Lane)}>{lanes.map(l=><option key={l}>{l}</option>)}</select></label>{lane==="INVESTIGATE"&&<Link href="/dashboard/briefs">Open Opportunity Brief →</Link>}{lane==="EXPERIMENT"&&<Link href="/dashboard/experiment">Plan a small experiment →</Link>}</article>)}</div>)}</section><section className="field-workspace-footer"><div><p className="eyebrow dark">YOUR FIELD CAN CHANGE</p><h2>Changing your mind is part of discovery.</h2><p>A possibility can move from curiosity to investigation, from investigation to experiment—or out of the active field entirely. The movement itself becomes useful evidence.</p></div><div><Link className="button dark-button" href="/start">Continue discovering →</Link><Link className="button outline-button" href="/blueprint">Take my field into the Blueprint →</Link></div></section><p className="workspace-boundary">{save==="saving"?"Saving field changes…":save==="saved"?"Field saved to your Discovery Record.":save==="local"?"Field changes are available in this browser session; sign in to save them.":"Your Discovery Field is connected to your Discovery Record."}</p></main>}