export type Possibility={
 title:string;world:"CAREER"|"BUSINESS"|"WHAT YOU KNOW"|"EXPERIENCE"|"UNEXPECTED";lane:"BUILD ON WHAT I KNOW"|"ONE STEP BEYOND"|"SURPRISE ME";
 desc:string;signals:string[];friction:string[];entry:string;attractive:string;watch:string;experiment:string;
};
export const possibilityUniverse:Possibility[]=[
["Fractional Strategic Adviser","CAREER","BUILD ON WHAT I KNOW","Bring senior judgment to a small number of organizations without taking on another full-time operating role.",["Independence","Income","Flexibility"],["Long hours","Office politics"],"Define one or two strategic problems you can solve and the organizations most likely to value your judgment.","Senior-level challenge and income with less operating responsibility.","Scope creep can recreate the workload you hoped to leave behind.","Write a one-page advisory offer and test it in three conversations."],
["Specialized Instructor","CAREER","BUILD ON WHAT I KNOW","Teach a subject you know deeply through an institution, association, company or private program.",["Teaching","Contribution","Learning"],["Management","Financial risk"],"Choose a subject and audience where your experience creates unusual credibility.","Teaching can preserve expertise, social connection and intellectual challenge.","Subject expertise and teaching skill are different; format and audience matter.","Deliver one guest session before pursuing a larger role."],
["Expert Witness or Technical Reviewer","CAREER","ONE STEP BEYOND","Apply specialized professional or industry knowledge to disputes, reviews, investigations or complex decisions.",["Intellectual challenge","Income","Independence"],["Employees","Fixed schedules"],"Identify where your expertise intersects with matters requiring independent judgment.","Focused assignments can reward deep experience without a conventional job.","Credential expectations, conflicts and legal exposure vary by field.","Interview two professionals who retain experts in your domain."],
["Portfolio Career","CAREER","SURPRISE ME","Combine two or three selective roles instead of forcing the next chapter into one job title.",["Flexibility","Independence","Contribution"],["Office politics","Repetition"],"Identify roles you would enjoy in smaller doses and design a weekly or seasonal mix.","Variety, autonomy and multiple forms of contribution.","Scheduling and income can fragment without deliberate structure.","Sketch an ideal month and test one component."],
["Specialty Research & Insight Practice","BUSINESS","ONE STEP BEYOND","Turn deep subject knowledge and investigative ability into focused research, intelligence briefs or decision support.",["Independence","Intellectual challenge","Learning"],["Employees","Fixed schedules"],"Choose a narrow problem and customer group, then begin with a small research engagement.","High autonomy, intellectual depth and low overhead.","Requires a credible niche and practical route to buyers.","Interview five potential buyers and draft one sample insight brief."],
["Expert-Led Learning Studio","BUSINESS","BUILD ON WHAT I KNOW","Package something you understand unusually well into workshops, private learning or executive education.",["Teaching","Creativity","Contribution"],["Commuting","Management"],"Start with one subject and one clearly defined audience.","Turns expertise into creative useful work without a large organization.","Demand should be tested before building a full program.","Deliver one 60–90 minute pilot workshop."],
["Micro-Consulting Practice","BUSINESS","BUILD ON WHAT I KNOW","Design a deliberately small advisory business around one valuable problem rather than recreating a full operating company.",["Independence","Income","Flexibility"],["Employees","Management"],"Select one high-value problem, one client type and a tightly bounded offer.","Can keep challenge and client impact while removing payroll and overhead.","Client acquisition and boundaries require discipline.","Offer one fixed-scope paid diagnostic to a warm prospect."],
["Niche Acquisition Entrepreneur","BUSINESS","SURPRISE ME","Acquire a small existing business rather than inventing one from zero, then reshape it around your preferred role.",["Building something","Income","Intellectual challenge"],["Repetition","Office politics"],"Study one small-business category where operations can be understood and delegated.","Existing customers and cash flow may reduce idea risk.","Capital, diligence, management and operating risk can be substantial.","Review ten real listings and build a no-buy investment thesis."],
["Expert-Led Experience Business","BUSINESS","ONE STEP BEYOND","Create small premium experiences around a subject, place, craft or body of expertise.",["Creativity","Teaching","Adventure"],["Employees","Repetition"],"Combine a subject you know with an audience seeking access, learning or immersion.","Blends expertise, curation and human connection.","Logistics, liability and customer acquisition can outweigh the creative appeal.","Host one invitation-only half-day pilot."],
["Methodology Productization","WHAT YOU KNOW","BUILD ON WHAT I KNOW","Turn a repeatable method or framework you have developed into a defined service, toolkit or training system.",["Creativity","Building something","Income"],["Employees","Commuting"],"Document the sequence you repeatedly use to produce a result.","Makes tacit know-how visible and potentially transferable.","A method needs evidence, clarity and a real buyer problem.","Map the method on one page and test it with three outsiders."],
["Knowledge Licensing Lab","WHAT YOU KNOW","SURPRISE ME","Explore whether original know-how, content, frameworks or processes could be licensed rather than delivered personally every time.",["Independence","Creativity","Income"],["Constant availability","Long hours"],"Inventory original materials and identify who might benefit from using them under defined terms.","Can separate value creation from hours worked.","Ownership, protectability, demand and licensing economics require careful review.","Choose one asset and interview a licensing or IP professional about feasibility."],
["Specialist Publication or Briefing","WHAT YOU KNOW","ONE STEP BEYOND","Build a focused publication, research letter, briefing service or knowledge product around expertise others value.",["Intellectual challenge","Creativity","Learning"],["Management","Employees"],"Choose a narrow audience with a recurring need for interpretation or insight.","Supports writing, research and authority building with low overhead.","Audience development and willingness to pay must be proven.","Publish three sample issues and recruit ten test readers."],
["Mentor-in-Residence","EXPERIENCE","BUILD ON WHAT I KNOW","Contribute experience to a school, accelerator, nonprofit or professional community in a bounded mentoring role.",["Contribution","Teaching","Meaning"],["Long hours","Management"],"Identify communities where your pattern recognition could accelerate others.","Meaningful contribution without taking over operations.","Poorly defined mentoring can become unpaid consulting or management.","Mentor one cohort or office-hour session."],
["Field-Based Learning Journey","EXPERIENCE","ONE STEP BEYOND","Build a season around learning something in the place where it is seriously practiced.",["Adventure","Learning","Travel"],["Repetition","Fixed schedules"],"Choose one serious curiosity and investigate where it is practiced or taught deeply.","Combines learning, travel and renewal without requiring monetization.","Cost, logistics and physical demands vary widely.","Plan a three-day local or regional version first."],
["Working Sabbatical","EXPERIENCE","SURPRISE ME","Design a temporary chapter combining learning, contribution and a limited project rather than conventional vacation or employment.",["Adventure","Meaning","Flexibility"],["Constant availability","Repetition"],"Choose a place or field and define one useful project plus one learning objective.","Creates novelty and purpose without demanding a permanent identity change.","Requires clear boundaries, logistics and financial planning.","Design a two-week prototype on paper with budget and daily rhythm."],
["Curated Salon or Learning Circle","UNEXPECTED","SURPRISE ME","Convenе a small recurring group around ideas, expertise, books, innovation or a specialized subject you care about.",["Learning","Contribution","Teaching"],["Management","Financial risk"],"Pick a subject and invite a deliberately small group of thoughtful participants.","Creates intellectual community and can lead to unforeseen collaborations.","It may remain a pursuit rather than a business—and that can be fine.","Host one 90-minute dinner or virtual salon."],
["Independent Project Producer","UNEXPECTED","ONE STEP BEYOND","Assemble temporary teams around interesting projects without owning a permanent organization.",["Creativity","Building something","Independence"],["Employees","Fixed schedules"],"Choose a project type where you can define outcomes and recruit specialists as needed.","Preserves creation and leadership while avoiding permanent headcount.","Still requires coordination, selling and project risk.","Produce one small project using two outside collaborators."],
["Apprentice-to-Expert Reset","UNEXPECTED","SURPRISE ME","Deliberately become a beginner in a demanding craft, technical field or intellectual discipline, then see where mastery leads.",["Learning","Adventure","Creativity"],["Repetition","Management"],"Choose something compelling enough that you would enjoy being bad at it for a while.","Restores curiosity and opens networks and identities that past experience may never have exposed.","Time, humility and training requirements can be significant.","Take one serious introductory class and interview a practitioner."],
["Community Venture Builder","UNEXPECTED","ONE STEP BEYOND","Use business experience to help launch a civic, cultural or mission-driven project with a defined beginning and end.",["Contribution","Building something","Meaning"],["Office politics","Constant availability"],"Find a concrete local problem where your organizing or commercial skills could unlock action.","Combines usefulness, challenge and community without requiring a lifelong role.","Mission projects can accumulate politics and unpaid obligations.","Join one bounded planning sprint before accepting leadership."],
["Curator or Collector-to-Educator","UNEXPECTED","SURPRISE ME","Turn a serious collecting or subject interest into talks, exhibitions, guides, research or educational experiences.",["Learning","Teaching","Creativity"],["Management","High pressure"],"Identify an interest where you have accumulated unusual knowledge, objects or perspective.","Transforms a private interest into contribution and connection.","Monetization may be limited; authenticity matters more than forcing a business model.","Create one short public guide or small exhibit for a test audience."]
].map(x=>({title:x[0],world:x[1],lane:x[2],desc:x[3],signals:x[4],friction:x[5],entry:x[6],attractive:x[7],watch:x[8],experiment:x[9]} as Possibility));
