"use client";
import {useMemo,useState} from "react";
import {Chrome} from "../components/SiteChrome";
import {possibilityUniverse} from "../../lib/discovery/possibilities";
import {buildDiscoveryProfile} from "../../lib/discovery/profile";

const choices=["I’m thinking about a new career.","I’d like to explore a business.","I’m curious what I could do with what I know.","I’m looking for something interesting or different.","I’m really not sure.","Surprise me."];
const more=["Independence","Intellectual challenge","Creativity","Income","Flexibility","Adventure","Meaning","Learning","Teaching","Building something","Travel","Contribution"];
const less=["Employees","Office politics","Commuting","Selling","Long hours","Fixed schedules","Management","Financial risk","Administrative work","Constant availability","Isolation","Repetition","High pressure"];
const possibilities=possibilityUniverse;
const reactions=["NOT ME","MAYBE","CURIOUS","SHOW ME MORE"] as const;
const rejectReasons=["Too familiar","Too much selling","Too social","Too much risk","Too much management","Income uncertainty","Doesn’t fit my lifestyle","Simply not interesting"];
const lanes=[
 {name:"BUILD ON WHAT I KNOW",desc:"Use experience you already have—but in a different shape.",ideas:["Independent Expert Adviser","Specialized Teaching Practice","Fractional Leadership"]},
 {name:"ONE STEP BEYOND",desc:"Move into adjacent territory that uses underlying strengths in a less obvious way.",ideas:["Research & Insight Studio","Expert-Led Experience Business","Niche Acquisition Search"]},
 {name:"SURPRISE ME",desc:"Deliberately step outside the possibilities you would normally think to search for.",ideas:["Field-Based Learning Venture","Knowledge Licensing Lab","Curated Expedition or Salon"]}
];
type Reaction=typeof reactions[number];

export default function Page(){
 const [stage,setStage]=useState(1),[pick,setPick]=useState("");
 const [wanted,setWanted]=useState<string[]>([]),[avoid,setAvoid]=useState<string[]>([]);
 const [index,setIndex]=useState(0),[rated,setRated]=useState<Record<number,Reaction>>({});
 const [rejecting,setRejecting]=useState(false),[rejectData,setRejectData]=useState<Record<number,string[]>>({});
 const [lane,setLane]=useState("");
 const [preview,setPreview]=useState(false);
 const toggle=(x:string,setter:React.Dispatch<React.SetStateAction<string[]>>)=>setter(s=>s.includes(x)?s.filter(v=>v!==x):[...s,x]);
 const ordered=useMemo(()=>[...possibilities].sort((a,b)=>{
   const laneBoost=(p:typeof possibilities[number])=>!lane?0:p.lane===lane?4:-1;
   const score=(p:typeof possibilities[number])=>p.signals.filter(x=>wanted.includes(x)).length+p.friction.filter(x=>avoid.includes(x)).length;
   return (score(b)+laneBoost(b))-(score(a)+laneBoost(a));
 }),[wanted,avoid,lane]);
 const advance=()=>{setRejecting(false);setPreview(false);if(index<ordered.length-1)setIndex(index+1);else setStage(5)};
 const rate=(r:Reaction)=>{setRated(v=>({...v,[index]:r}));if(r==="NOT ME"){setRejecting(true);setPreview(false)}else if(r==="CURIOUS"||r==="SHOW ME MORE"){setPreview(true)}else advance()};
 const toggleReject=(x:string)=>setRejectData(v=>({...v,[index]:(v[index]||[]).includes(x)?(v[index]||[]).filter(y=>y!==x):[...(v[index]||[]),x]}));
 const strong=Object.values(rated).filter(x=>x==="CURIOUS"||x==="SHOW ME MORE").length;
 const profile=useMemo(()=>buildDiscoveryProfile(wanted,avoid),[wanted,avoid]);
 return <Chrome><main><section className="start-wrap">
 <div className="discovery-progress"><span>DISCOVER</span><i className={stage>=4?"on":""}>GET INSPIRED</i><i className={stage>=5?"on":""}>IMAGINE</i><i>DESIGN</i></div>
 {stage===1&&<><p className="eyebrow dark">START DISCOVERING</p><h1>Let’s find a place to begin.</h1><p className="lead darklead">You don’t have to know where you’re going. Just tell us what sounds closest to where you are today.</p><div className="choice-grid">{choices.map(x=><button onClick={()=>setPick(x)} className={pick===x?"choice active":"choice"} key={x}>{x}</button>)}</div><button disabled={!pick} className="button gold" onClick={()=>setStage(2)}>Continue →</button></>}
 {stage===2&&<><p className="eyebrow dark">DISCOVER · 01</p><h1>What would you like more of?</h1><p className="lead darklead">Choose anything that catches your attention. Don’t overthink it.</p><div className="tag-grid">{more.map(x=><button onClick={()=>toggle(x,setWanted)} className={wanted.includes(x)?"tag active":"tag"} key={x}>{x}</button>)}</div><div className="start-actions"><button className="button text-button" onClick={()=>setStage(1)}>← Back</button><button disabled={!wanted.length} className="button gold" onClick={()=>setStage(3)}>Continue →</button></div></>}
 {stage===3&&<><p className="eyebrow dark">DISCOVER · 02</p><h1>What would you be happy to leave behind?</h1><p className="lead darklead">What you don’t want can be just as useful as what you do want.</p><div className="tag-grid">{less.map(x=><button onClick={()=>toggle(x,setAvoid)} className={avoid.includes(x)?"tag active":"tag"} key={x}>{x}</button>)}</div><div className="start-actions"><button className="button text-button" onClick={()=>setStage(2)}>← Back</button><button className="button gold" onClick={()=>{setIndex(0);setStage(4)}}>Show me possibilities →</button></div></>}
 {stage===4&&<><p className="eyebrow dark">GET INSPIRED</p><h1>Let’s try something.</h1><p className="lead darklead">These aren’t verdicts or recommendations. They’re possibilities to react to. Your reactions help us learn where to look next.</p><div className="possibility-reveal"><div className="possibility-count">{index+1} / {ordered.length}</div><p className="eyebrow dark">{ordered[index].world} · {ordered[index].lane}</p><h2>{ordered[index].title}</h2><p>{ordered[index].desc}</p><div className="why-box"><b>Why we’re showing you this</b><p>{ordered[index].signals.filter(x=>wanted.includes(x)).slice(0,3).join(" · ")||"It stretches beyond the most obvious path."}{ordered[index].friction.some(x=>avoid.includes(x))?" · It may also avoid some of the friction you told us you want less of.":""}</p></div><div className="reaction-buttons">{reactions.map(r=><button key={r} onClick={()=>rate(r)}>{r}</button>)}</div>{preview&&<div className="deep-preview"><div className="preview-kicker">POSSIBILITY PREVIEW</div><h3>{ordered[index].title}</h3><div className="preview-grid"><article><b>WHAT IT COULD LOOK LIKE</b><p>{ordered[index].entry}</p></article><article><b>WHAT MAY BE ATTRACTIVE</b><p>{ordered[index].attractive}</p></article><article><b>WHAT TO WATCH</b><p>{ordered[index].watch}</p></article><article><b>A SMALL WAY TO TEST IT</b><p>{ordered[index].experiment}</p></article></div><div className="preview-actions"><button className="button text-button" onClick={()=>{setPreview(false);advance()}}>Interesting—keep exploring →</button><a className="button dark-button" href="/blueprint">I want deeper research like this →</a></div></div>}{rejecting&&<div className="reject-panel"><b>Helpful. What made this a “Not Me”?</b><p>Choose anything that applies. Rejection helps us improve the next round.</p><div className="reject-tags">{rejectReasons.map(x=><button className={(rejectData[index]||[]).includes(x)?"active":""} onClick={()=>toggleReject(x)} key={x}>{x}</button>)}</div><button className="button dark-button" onClick={advance}>Use this and continue →</button></div>}</div><button className="button text-button" onClick={()=>setStage(3)}>← Adjust my answers</button></>}
 {stage===5&&<><p className="eyebrow dark">YOUR FIRST DISCOVERY SIGNALS</p><h1>We’re starting to notice a pattern.</h1><div className="signal-panel"><div><span>YOU ASKED FOR MORE</span><strong>{wanted.slice(0,4).join(" · ")||"Room to explore"}</strong></div><div><span>YOU’D RATHER LEAVE BEHIND</span><strong>{avoid.slice(0,4).join(" · ")||"Nothing specific yet"}</strong></div><div><span>IDEAS THAT CAUGHT YOUR ATTENTION</span><strong>{strong} of {ordered.length} initial possibilities</strong></div></div><div className="profile-card"><div className="profile-head"><div><p className="eyebrow dark">YOUR EMERGING DISCOVERY PROFILE</p><h2>Not a label. A pattern we can learn from.</h2></div><p>{profile.summary[0]}</p></div><div className="axis-list">{profile.axes.map(a=><div className="axis" key={a.left}><div className="axis-labels"><span>{a.left}</span><span>{a.right}</span></div><div className="axis-track"><i style={{left:((a.value+4)/8*100)+"%"}} /></div></div>)}</div><p className="profile-note">{profile.summary[1]} {profile.summary[2]}</p></div><div className="pattern-copy"><h2>Now discovery can get more interesting.</h2><p>We can follow the threads that caught your attention, deliberately introduce adjacent ideas, and occasionally take you somewhere less obvious. A rejection is useful too—it tells us where <em>not</em> to keep looking.</p><blockquote>“I don’t know” can begin to become “I never thought of that.”</blockquote></div><div className="next-lanes"><p className="eyebrow dark">WHERE SHOULD WE LOOK NEXT?</p><h2>Choose how far you want us to stretch.</h2><div className="lane-grid">{lanes.map(x=><button className={lane===x.name?"lane active":"lane"} onClick={()=>setLane(x.name)} key={x.name}><span>{x.name}</span><p>{x.desc}</p><small>{x.ideas.join(" · ")}</small></button>)}</div>{lane&&<div className="lane-confirm"><b>{lane}</b><p>{lane==="BUILD ON WHAT I KNOW"?"We’ll keep the next round closer to your existing experience while changing the role, structure or business model.":lane==="ONE STEP BEYOND"?"We’ll use the patterns we noticed, but deliberately cross into adjacent fields and less obvious applications.":"We’ll loosen the connection to familiar titles and search for underlying-fit possibilities you would be unlikely to type into a search box."}</p><button className="button gold" onClick={()=>{setRated({});setRejectData({});setIndex(0);setStage(4)}}>Explore this direction →</button></div>}</div><div className="start-actions"><a className="button dark-button" href="/blueprint">See where this can lead →</a></div></>}
 <p className="privacy-note">Build 6 demonstrates the reaction-driven discovery loop in your browser. Your selections in this preview are not yet written to the secure customer database. Production persistence and matching will be connected only after the interaction model passes review.</p>
 </section></main></Chrome>
}
